### PR TITLE
Port to 1.20.4 & refine Chinese & Japanese translations

### PR DESCRIPTION
**Pull request by BillStark001**
Hi there. I've updated the mod to newest version and updated the language files.
Hope this time the commit history meets your requirement :D

### CODE REVIEW

**Comment by charlyb01** [comment]
Hello! Thank you for your contribution, the history looks great. I will take a better look at it tomorrow and merge it =D

**Comment by BillStark001** [comment]
Wait, I found something very weird.
After loading the mod into the game, I found some of the C418 musics are unable to play and the settings panel looks like this:
screenshot
The following is the full log:
[log_1204.txt](https://github.com/sf-inc/music_control/files/13748071/log_1204.txt)
Since I cannot reproduce this issue in the development environment, I'm not sure what to do. It maybe some mods or Minecraft itself changed the resource keys, but I've found no changelogs on the Wiki.
I'll take time to investigate on this issue afterwards.

**Comment by charlyb01** [comment]
I will take a look tomorrow. I'm pretty sure they just renamed the c418 music with their actual name instead of "creative1", "creative2", ... The change shouldn't be really hard.

**Comment by BillStark001** [comment]
Ok, I found the reason. Seems Mojang did rename the keys ([link](https://minecraft.wiki/w/Sounds.json/Java_Edition_values?diff=prev&oldid=2380978)), but gradle's resource file is the old one so I didn't notice it :D

**Comment by charlyb01** [comment]
Thanks again for your work! =)

**Pull request merged**
